import type { Metadata } from "next"
import "./globals.css"
import Nav from "@/components/navigation/Nav"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/providers/ThemeProvider"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children}: Readonly<{
  children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className='px-6 max-w-7xl mx-auto'>
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            >
        <Nav />
        {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
